name: Decompose_006
language: Close the microwave
problem: Libero
problem_folder: tasks/Decompose/Decompose_006
bddl_file: task.bddl
init_states_file: task.pruned_init
category: TD
anchor_suite: libero_10
metadata_file: ../../tasks/Decompose/Decompose_006/task_meta.yaml
eval_rules_file: ../../tasks/Decompose/Decompose_006/eval_rules.yaml
canonical_task_signature: libero_10_kitchen_scene6|frozenset({close(microwave_1)})
eval_category: Task
source_benchmark: TaskDecomposition
collection_category: Decompose
legacy_task_id: TDL10_006
