name: Decompose_012
language: Put the cream cheese box in the basket
problem: Libero
problem_folder: tasks/Decompose/Decompose_012
bddl_file: task.bddl
init_states_file: task.pruned_init
category: TD
anchor_suite: libero_10
metadata_file: ../../tasks/Decompose/Decompose_012/task_meta.yaml
eval_rules_file: ../../tasks/Decompose/Decompose_012/eval_rules.yaml
canonical_task_signature: libero_10_living_room_scene2|frozenset({in(cream_cheese_1,
  basket_1_contain_region)})
eval_category: Task
source_benchmark: TaskDecomposition
collection_category: Decompose
legacy_task_id: TDL10_013
